{{- /*
  Renders the db-credentials Secret used by account-db, order-db, and app deployments.
  Uses secrets.dbCredentials; secret data via stringData (plain text, Kubernetes base64-encodes).
  Override in production: --set secrets.dbCredentials.stringData.postgres-password="..."
*/ -}}
{{- $sc := .Values.secrets.dbCredentials }}
{{- if and $sc (or $sc.stringData $sc.data) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sc.name }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if $sc.stringData }}
stringData:
  {{- toYaml $sc.stringData | nindent 2 }}
{{- else }}
data:
  {{- toYaml $sc.data | nindent 2 }}
{{- end }}
{{- end }}
